services:
  - type: web
    name: warera-build-helper
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./startup.sh"
    envVars:
      - key: FLASK_APP
        value: warera/app.py
      - key: FLASK_ENV
        value: production
